config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :albums
  resources :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "albums#index"
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :tracks, dependent: :destroy
  accepts_nested_attributes_for :tracks, reject_if: :all_blank, allow_destroy: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums, dependent: :destroy
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all.order(:release_year)
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
    10.times { @album.tracks.build }
  end

  # GET /albums/1/edit
  def edit
    5.times { @album.tracks.build }
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy!

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:name, :release_year, :image_url, :artist_id,
                                    tracks_attributes: [:id, :name, :track_number, :_destroy])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all.order :name
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy!

    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: %i[ show edit update destroy ]

  # GET /tracks or /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1 or /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks or /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to track_url(@track), notice: "Track was successfully created." }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1 or /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to track_url(@track), notice: "Track was successfully updated." }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1 or /tracks/1.json
  def destroy
    @track.destroy!

    respond_to do |format|
      format.html { redirect_to tracks_url, notice: "Track was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def track_params
      params.require(:track).permit(:name, :track_number, :album_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/albums/_album.html.erb
<div class="col-md-4">
  <div id="<%= dom_id album %>" class="card m-3" >
    <img src="<%= album.image_url %>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= album.name %></h5>
      <p class="card-text">
        <strong><%= album.artist.name %></strong>
      </p>
      <p class="card-text">
        <strong>Release year:</strong>
        <%= album.release_year %>
      </p>
      <%= link_to "Show", album, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>
  <div class="row">

    <div class="mb-3 col-md-6">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3 col-md-6">
      <%= form.label :artist_id, class: 'form-label' %>
      <%= form.select :artist_id, Artist.all.order(:name).collect { |artist| [artist.name, artist.id] },
                      {include_blank: 'Valitse artisti'}, class: 'form-control' %>
    </div>

    <div class="mb-3 col-md-6">
      <%= form.label :release_year, class: 'form-label' %>
      <%= form.number_field :release_year, class: 'form-control' %>
    </div>

    <div class="mb-3 col-md-6">
      <%= form.label :image_url, class: 'form-label' %>
      <%= form.text_field :image_url, class: 'form-control' %>
    </div>

  </div>

  <h3>Tracks</h3>

  <%= form.fields_for :tracks do |track_form| %>
  <div class="row">
    <div class="mb-3 col-md-3">
      <%= track_form.label :track_number, class: 'form-label' %>
      <%= track_form.number_field :track_number, class: 'form-control' %>
    </div>
    <div class="mb-3 col-md-6">
      <%= track_form.label :name, class: 'form-label' %>
      <%= track_form.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <%= track_form.label :_destroy, class: 'form-check-label' %>
      <div>
        <%= track_form.check_box :_destroy, class: 'form-check-input' %>
      </div>
    </div>

  </div>
    <% end %>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/index.html.erb
<p class="text-success"><%= notice %></p>

<h1>Albums</h1>

<div id="albums" class="row">
  <% @albums.each do |album| %>
    <%= render album %>
  <% end %>
</div>
<div class="container-fluid mt-4">
  <%= link_to "New album", new_album_path, class: "btn btn-primary" %>
</div>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/show.html.erb
<p class="text-success"><%= notice %></p>

<%= render @album %>

<h3>Tracks</h3>
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
  </tr>
  </thead>
  <tbody>
  <% @album.tracks.each do |track| %>
    <tr>
      <td><%= track.track_number %></td>
      <td><%= track.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div>
  <%= link_to "Edit this album", edit_album_path(@album) %> |
  <%= link_to "Back to albums", albums_path %>

  <%= button_to "Destroy this album", @album, method: :delete, class: "mt-5 btn btn-danger" %>
</div>

app/views/artists/_artist.html.erb
<div id="<%= dom_id artist %>">
  <p>
    <strong>Name:</strong>
    <%= artist.name %>
  </p>

</div>

app/views/artists/_form.html.erb
<%= form_with(model: artist) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>

  <div class="row">
    <div class="mb-3 col-md-6">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Show this artist", @artist %> |
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/index.html.erb
<p class="text-success"><%= notice %></p>

<h1>Artists</h1>

<div id="artists" class="container-fluid">
  <ul>
    <% @artists.each do |artist| %>
      <li>
        <%= link_to artist.name, artist %>
      </li>
    <% end %>
  </ul>
</div>
<div class="container-fluid mt-4">
  <%= link_to "New artist", new_artist_path, class: "btn btn-primary" %>
</div>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/show.html.erb
<p class="text-success"><%= notice %></p>

<%= render @artist %>

<div>
  <%= link_to "Edit this artist", edit_artist_path(@artist) %> |
  <%= link_to "Back to artists", artists_path %>

  <%= button_to "Destroy this artist", @artist, method: :delete, class: "mt-5 btn btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Levyloota</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="text-center">
      <h1>LEVYLOOTA</h1>
    </header>
    <main class="container p-3">

      <nav>
        <ul class="nav">
          <li class="nav-item">
            <%= link_to "Artists", artists_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Albums", albums_path, class: 'nav-link' %>
          </li>
        </ul>
      </nav>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved:</h2>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tracks/_form.html.erb
<%= form_with(model: track) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :track_number, style: "display: block" %>
    <%= form.number_field :track_number %>
  </div>

  <div>
    <%= form.label :album_id, style: "display: block" %>
    <%= form.text_field :album_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/_track.html.erb
<div id="<%= dom_id track %>" class="row">
  <div class="col">
    <strong>Track number:</strong>
    <%= track.track_number %>
  </div>
  <div class="col">
    <strong>Name:</strong>
    <%= track.name %>
  </div>
</div>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Show this track", @track %> |
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tracks</h1>

<div id="tracks">
  <% @tracks.each do |track| %>
    <%= render track %>
    <p>
      <%= link_to "Show this track", track %>
    </p>
  <% end %>
</div>

<%= link_to "New track", new_track_path %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @track %>

<div>
  <%= link_to "Edit this track", edit_track_path(@track) %> |
  <%= link_to "Back to tracks", tracks_path %>

  <%= button_to "Destroy this track", @track, method: :delete %>
</div>